AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**"
    - "db/**/*"
    - "vendor/bundle/**/*"

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"

Metrics/MethodLength:
  CountAsOne: ["array", "heredoc"]
  Max: 15

Style/Documentation:
  Enabled: false

