default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/k8s_hw_1_development.sqlite3

test:
  <<: *default
  database: storage/k8s_hw_1_test.sqlite3

production:
  <<: *default
  database: storage/k8s_hw_1_production.sqlite3
