apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rails-app.fullname" . }}-config
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
